
environment:
  manifold_type: "sphere"  
  params:
    radius: 2.0           
    R: 3.0               
    r: 1.0               
    width: 1.0           
    dimension: 2         
  
  max_episode_steps: 500  
  reward_scale: 1.0      

visualization:
  render_mode: "human"    
  window_size: [800, 600] 
  frame_scale: 0.3        
  show_curvature: true    
  colors:
    trajectory: "red"
    frame1: "blue"
    frame2: "green"
    surface: "gray"
  alpha: 0.2             

training:
  algorithm: "ppo"        
  num_episodes: 1000      
  batch_size: 64          
  learning_rate: 0.001    
  gamma: 0.99            
  gae_lambda: 0.95       
  clip_range: 0.2        
  
  network:
    hidden_sizes: [64, 64]
    activation: "relu"
    
logging:
  log_dir: "logs"        
  save_frequency: 100    
  eval_frequency: 50     
  verbose: true         